name: iOS Build and Upload to TestFlight

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.1"
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install gems (iOS)
        working-directory: ios
        run: bundle install

      - name: Create and unlock CI keychain
        working-directory: ios
        shell: bash
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          set -euo pipefail
          KEYCHAIN_NAME=ci.keychain-db

          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"

          # tornar o keychain pesquis√°vel e default
          security list-keychains -d user -s "$KEYCHAIN_NAME" login.keychain-db
          security default-keychain -d user -s "$KEYCHAIN_NAME"

      - name: Run fastlane teste
        working-directory: ios
        env:
          CI: "true"
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_BASE64: ${{ secrets.ASC_KEY_BASE64 }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: bundle exec fastlane teste